import type { Control } from '../types'

export const mockControls: Control[] = [
  {
    id: '01901234-0000-7000-8000-000000000001',
    code: 'O2C-AR-C001',
    name: '매출채권 월말 잔액 조정',
    description: '매월 말 매출채권 원장과 총계정원장 잔액을 대사하고 차이를 검토한다.',
    objective: '매출채권 잔액의 정확성 및 완전성 확보',
    owner_name: '김재무',
    risk_id: 'r-001',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: true,
    activity_supervision: false,
    related_accounts: '매출채권',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['C', 'V'],
    process_code: 'O2C',
    sub_process_code: 'O2C-AR',
    risk_level: 'HR',
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000002',
    code: 'O2C-REV-C001',
    name: '수익 인식 검토',
    description: '월별 수익 인식 기준 충족 여부를 계약서와 대조하여 검토한다.',
    objective: '수익 인식 기준 준수',
    owner_name: '이회계',
    risk_id: 'r-002',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매출, 선수수익',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['O', 'C', 'V'],
    process_code: 'O2C',
    sub_process_code: 'O2C-REV',
    risk_level: 'SR',
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000003',
    code: 'O2C-REV-C002',
    name: '수익 자동 인식 시스템 검증',
    description: 'ERP 수익 자동 인식 로직의 정확성을 분기별로 검증한다.',
    objective: 'IT 자동 통제 신뢰성 확보',
    owner_name: '박IT',
    risk_id: 'r-002',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'A',
    frequency: 'Q',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매출',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['O', 'E'],
    process_code: 'O2C',
    sub_process_code: 'O2C-REV',
    risk_level: 'HR',
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000004',
    code: 'O2C-CR-C001',
    name: '신규 거래처 신용 한도 승인',
    description: '신규 거래처의 신용 한도를 여신 정책에 따라 승인한다.',
    objective: '대손 위험 최소화',
    owner_name: '박영업',
    risk_id: 'r-003',
    is_key_control: false,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매출채권',
    related_systems: null,
    euc_description: null,
    assertions: ['E', 'V'],
    process_code: 'O2C',
    sub_process_code: 'O2C-CR',
    risk_level: 'MR',
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000005',
    code: 'P2P-AP-C001',
    name: '매입채무 월말 잔액 조정',
    description: '월말 매입채무 원장과 총계정원장을 대사하고 차이를 검토한다.',
    objective: '매입채무 완전성 및 정확성',
    owner_name: '최구매',
    risk_id: 'r-004',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: true,
    activity_supervision: false,
    related_accounts: '매입채무',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['C', 'V'],
    process_code: 'P2P',
    sub_process_code: 'P2P-AP',
    risk_level: 'HR',
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000006',
    code: 'P2P-PO-C001',
    name: '구매주문서 3방향 대사',
    description: '구매주문서, 수령증, 청구서를 3방향 대사하여 지급을 승인한다.',
    objective: '미승인 지출 방지',
    owner_name: '최구매',
    risk_id: 'r-005',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'A',
    frequency: 'O',
    ipe_relevant: 'N/A',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매입채무, 재고자산',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'C', 'O'],
    process_code: 'P2P',
    sub_process_code: 'P2P-PO',
    risk_level: 'HR',
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000007',
    code: 'P2P-PO-C002',
    name: '긴급 구매 사후 승인',
    description: '긴급 구매 발생 후 5 영업일 이내 관리자 사후 승인을 득한다.',
    objective: '긴급 구매에 대한 통제 유지',
    owner_name: '정관리',
    risk_id: 'r-005',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: true,
    related_accounts: '매입채무',
    related_systems: null,
    euc_description: null,
    assertions: ['E'],
    process_code: 'P2P',
    sub_process_code: 'P2P-PO',
    risk_level: 'MR',
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000008',
    code: 'P2P-PAY-C001',
    name: '지급 한도 초과 이중 승인',
    description: '100만원 초과 지급 건은 재무팀장과 CFO 이중 승인이 필요하다.',
    objective: '대규모 미승인 지출 방지',
    owner_name: '김재무',
    risk_id: 'r-006',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '현금및현금성자산',
    related_systems: '인터넷뱅킹',
    euc_description: null,
    assertions: ['E', 'O'],
    process_code: 'P2P',
    sub_process_code: 'P2P-PAY',
    risk_level: 'SR',
    created_at: '2026-05-02T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000009',
    code: 'R2R-GL-C001',
    name: '월말 결산 분개 검토',
    description: '월말 수기 분개 전표를 재무팀장이 검토하고 승인한다.',
    objective: '오류·부정 분개 방지',
    owner_name: '이회계',
    risk_id: 'r-007',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '전계정',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'C', 'O'],
    process_code: 'R2R',
    sub_process_code: 'R2R-GL',
    risk_level: 'SR',
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000010',
    code: 'R2R-GL-C002',
    name: '비용 계정 예산 대비 실적 분석',
    description: '월별 주요 비용 계정의 예산 대비 실적 차이를 분석하고 이상 항목을 조사한다.',
    objective: '비용 과대·과소 계상 예방',
    owner_name: '정관리',
    risk_id: 'r-007',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'Y',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: true,
    related_accounts: '판관비',
    related_systems: 'ERP(SAP)',
    euc_description: 'Excel 분석 보고서',
    assertions: ['C', 'V'],
    process_code: 'R2R',
    sub_process_code: 'R2R-GL',
    risk_level: 'MR',
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000011',
    code: 'R2R-CLOSE-C001',
    name: '계정 잔액 확인서 수신',
    description: '연말 주요 거래처 및 금융기관으로부터 잔액 확인서를 수신하고 대사한다.',
    objective: '잔액 실재성 확인',
    owner_name: '이회계',
    risk_id: 'r-008',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'A',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: true,
    activity_supervision: false,
    related_accounts: '매출채권, 매입채무, 차입금',
    related_systems: null,
    euc_description: null,
    assertions: ['E', 'V'],
    process_code: 'R2R',
    sub_process_code: 'R2R-CLOSE',
    risk_level: 'HR',
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000012',
    code: 'R2R-CLOSE-C002',
    name: '재무제표 공시 검토',
    description: '재무제표 주석 공시 항목의 정확성 및 완전성을 법무팀과 공동 검토한다.',
    objective: '공시 오류 방지',
    owner_name: '김재무',
    risk_id: 'r-008',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'Q',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '전계정',
    related_systems: null,
    euc_description: null,
    assertions: ['P', 'C'],
    process_code: 'R2R',
    sub_process_code: 'R2R-CLOSE',
    risk_level: 'SR',
    created_at: '2026-05-03T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000013',
    code: 'HR-PAY-C001',
    name: '급여 대장 검토 및 승인',
    description: '월별 급여 대장을 HR팀장과 CFO가 검토·승인한다.',
    objective: '급여 과지급·중복지급 방지',
    owner_name: '오인사',
    risk_id: 'r-009',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '급여, 퇴직급여충당부채',
    related_systems: 'HR시스템',
    euc_description: null,
    assertions: ['E', 'C', 'O'],
    process_code: 'HR',
    sub_process_code: 'HR-PAY',
    risk_level: 'HR',
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000014',
    code: 'HR-PAY-C002',
    name: '급여 계좌 변경 이중 확인',
    description: '급여 수령 계좌 변경 요청 시 신분 확인 및 이중 승인을 받는다.',
    objective: '급여 횡령 방지',
    owner_name: '오인사',
    risk_id: 'r-009',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: true,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '급여',
    related_systems: 'HR시스템',
    euc_description: null,
    assertions: ['E'],
    process_code: 'HR',
    sub_process_code: 'HR-PAY',
    risk_level: 'SR',
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000015',
    code: 'HR-TERM-C001',
    name: '퇴직자 시스템 접근권한 즉시 회수',
    description: '퇴직 당일 IT팀이 모든 시스템 계정을 비활성화한다.',
    objective: '퇴직자 비인가 접근 차단',
    owner_name: '박IT',
    risk_id: 'r-010',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: true,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: 'AD, ERP, 그룹웨어',
    euc_description: null,
    assertions: ['E'],
    process_code: 'HR',
    sub_process_code: 'HR-TERM',
    risk_level: 'HR',
    created_at: '2026-05-04T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000016',
    code: 'ITG-ACC-C001',
    name: '특권 계정 반기별 검토',
    description: 'IT 관리자·DBA 등 특권 계정 목록을 반기별로 검토하고 불필요 계정을 삭제한다.',
    objective: '과도한 접근 권한 방지',
    owner_name: '박IT',
    risk_id: 'r-011',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'Q',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: true,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: 'AD, ERP, DB서버',
    euc_description: null,
    assertions: ['E', 'C'],
    process_code: 'ITG',
    sub_process_code: 'ITG-ACC',
    risk_level: 'HR',
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000017',
    code: 'ITG-ACC-C002',
    name: 'ERP 접근 권한 직무 분리 점검',
    description: '분기별로 ERP 내 직무 분리 충돌(SOD) 여부를 점검한다.',
    objective: '직무 분리 원칙 준수',
    owner_name: '박IT',
    risk_id: 'r-011',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'IT',
    frequency: 'Q',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: true,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E'],
    process_code: 'ITG',
    sub_process_code: 'ITG-ACC',
    risk_level: 'HR',
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000018',
    code: 'ITG-CHG-C001',
    name: 'IT 변경 관리 승인 프로세스',
    description: '프로덕션 시스템 변경은 변경관리위원회(CAB) 승인 후 적용한다.',
    objective: '비인가 시스템 변경 방지',
    owner_name: '박IT',
    risk_id: 'r-012',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N/A',
    activity_approval: true,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: 'ERP, WAS, DB서버',
    euc_description: null,
    assertions: ['E', 'O'],
    process_code: 'ITG',
    sub_process_code: 'ITG-CHG',
    risk_level: 'SR',
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000019',
    code: 'ITG-BCP-C001',
    name: '데이터 백업 일별 확인',
    description: '매일 백업 성공 여부를 모니터링 대시보드에서 확인하고 실패 시 즉시 조치한다.',
    objective: '데이터 손실 방지',
    owner_name: '박IT',
    risk_id: 'r-013',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'IT',
    frequency: 'D',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: 'DB서버, 백업시스템',
    euc_description: null,
    assertions: ['E'],
    process_code: 'ITG',
    sub_process_code: 'ITG-BCP',
    risk_level: 'MR',
    created_at: '2026-05-05T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000020',
    code: 'O2C-INV-C001',
    name: '재고 실사 결과 검토',
    description: '분기별 재고 실사 결과를 ERP 장부와 대사하고 차이를 분석한다.',
    objective: '재고자산 실재성 및 정확성 확보',
    owner_name: '한물류',
    risk_id: 'r-014',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'Q',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: true,
    activity_master_data: false,
    activity_reconciliation: true,
    activity_supervision: false,
    related_accounts: '재고자산',
    related_systems: 'ERP(SAP), WMS',
    euc_description: null,
    assertions: ['E', 'C', 'V'],
    process_code: 'O2C',
    sub_process_code: 'O2C-INV',
    risk_level: 'HR',
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000021',
    code: 'O2C-INV-C002',
    name: '재고 평가 방법 일관성 검토',
    description: '연간 재고 평가 방법 변경 여부를 확인하고 회계 정책과의 일치성을 검토한다.',
    objective: '회계 정책 일관성 유지',
    owner_name: '이회계',
    risk_id: 'r-014',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'A',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '재고자산',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['V', 'P'],
    process_code: 'O2C',
    sub_process_code: 'O2C-INV',
    risk_level: 'LR',
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000022',
    code: 'P2P-INV-C001',
    name: '매입 인보이스 중복 지급 자동 점검',
    description: 'ERP가 인보이스 번호·금액·공급업체 조합으로 중복 지급을 자동 차단한다.',
    objective: '중복 지급 방지',
    owner_name: null,
    risk_id: 'r-015',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'A',
    frequency: 'O',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매입채무',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'O'],
    process_code: 'P2P',
    sub_process_code: 'P2P-INV',
    risk_level: 'MR',
    created_at: '2026-05-06T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000023',
    code: 'R2R-FA-C001',
    name: '유형자산 실사',
    description: '연 1회 유형자산 실사를 실시하고 장부와 대사한다.',
    objective: '유형자산 실재성 확인',
    owner_name: '한물류',
    risk_id: 'r-016',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'A',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: true,
    activity_master_data: false,
    activity_reconciliation: true,
    activity_supervision: false,
    related_accounts: '유형자산',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'V'],
    process_code: 'R2R',
    sub_process_code: 'R2R-FA',
    risk_level: 'MR',
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000024',
    code: 'R2R-FA-C002',
    name: '감가상각 계산 검토',
    description: '월별 감가상각 계산 결과를 이전 월과 비교하고 이상 항목을 조사한다.',
    objective: '감가상각 정확성 확보',
    owner_name: '이회계',
    risk_id: 'r-016',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'M',
    ipe_relevant: 'Y',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '유형자산, 감가상각비',
    related_systems: 'ERP(SAP)',
    euc_description: 'Excel 감가상각 명세서',
    assertions: ['V', 'C'],
    process_code: 'R2R',
    sub_process_code: 'R2R-FA',
    risk_level: 'LR',
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000025',
    code: 'HR-REC-C001',
    name: '신규 채용 배경 조사',
    description: '신규 임직원 채용 시 학력·경력·범죄 이력을 외부 기관을 통해 조사한다.',
    objective: '부적격자 채용 방지',
    owner_name: '오인사',
    risk_id: 'r-017',
    is_key_control: false,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: true,
    activity_physical: true,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: null,
    euc_description: null,
    assertions: ['E'],
    process_code: 'HR',
    sub_process_code: 'HR-REC',
    risk_level: 'LR',
    created_at: '2026-05-07T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000026',
    code: 'ITG-SEC-C001',
    name: '취약점 스캔 및 패치 관리',
    description: '월별 취약점 스캔을 실시하고 Critical 취약점은 30일 이내 패치한다.',
    objective: '사이버 보안 위협 차단',
    owner_name: '박IT',
    risk_id: 'r-018',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'IT',
    frequency: 'M',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: '전체 인프라',
    euc_description: null,
    assertions: ['E'],
    process_code: 'ITG',
    sub_process_code: 'ITG-SEC',
    risk_level: 'HR',
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000027',
    code: 'O2C-COL-C001',
    name: '연체 채권 주간 모니터링',
    description: '30일 이상 연체 채권을 주간 보고서로 영업팀과 공유하고 회수 계획을 수립한다.',
    objective: '대손 위험 조기 포착',
    owner_name: '박영업',
    risk_id: 'r-019',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'W',
    ipe_relevant: 'N',
    activity_approval: false,
    activity_verification: false,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: true,
    related_accounts: '매출채권',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'V'],
    process_code: 'O2C',
    sub_process_code: 'O2C-COL',
    risk_level: 'MR',
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000028',
    code: 'P2P-VEND-C001',
    name: '공급업체 마스터 변경 이중 승인',
    description: '공급업체 계좌번호 등 마스터 정보 변경은 구매팀장과 재무팀이 이중 승인한다.',
    objective: '공급업체 마스터 변경을 통한 횡령 방지',
    owner_name: '최구매',
    risk_id: 'r-020',
    is_key_control: true,
    preventive_detective: 'P',
    auto_manual: 'M',
    frequency: 'O',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: true,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '매입채무',
    related_systems: 'ERP(SAP)',
    euc_description: null,
    assertions: ['E', 'O'],
    process_code: 'P2P',
    sub_process_code: 'P2P-VEND',
    risk_level: 'SR',
    created_at: '2026-05-08T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000029',
    code: 'R2R-TAX-C001',
    name: '법인세 계산 외부 검토',
    description: '연간 법인세 계산서를 세무법인에 의뢰하여 검토받고 CFO가 최종 승인한다.',
    objective: '세무 위험 및 과소 납부 방지',
    owner_name: '김재무',
    risk_id: 'r-021',
    is_key_control: true,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'A',
    ipe_relevant: 'N',
    activity_approval: true,
    activity_verification: true,
    activity_physical: false,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: '법인세비용, 미지급법인세',
    related_systems: null,
    euc_description: null,
    assertions: ['C', 'V', 'P'],
    process_code: 'R2R',
    sub_process_code: 'R2R-TAX',
    risk_level: 'HR',
    created_at: '2026-05-09T00:00:00Z',
  },
  {
    id: '01901234-0000-7000-8000-000000000030',
    code: 'ITG-DR-C001',
    name: 'DR 훈련 연간 실시',
    description: '연 1회 재해복구(DR) 훈련을 실시하고 복구 목표 시간(RTO) 준수 여부를 검증한다.',
    objective: '사업 연속성 확보',
    owner_name: '박IT',
    risk_id: 'r-022',
    is_key_control: false,
    preventive_detective: 'D',
    auto_manual: 'M',
    frequency: 'A',
    ipe_relevant: 'N/A',
    activity_approval: false,
    activity_verification: true,
    activity_physical: true,
    activity_master_data: false,
    activity_reconciliation: false,
    activity_supervision: false,
    related_accounts: null,
    related_systems: '전체 인프라',
    euc_description: null,
    assertions: ['E'],
    process_code: 'ITG',
    sub_process_code: 'ITG-DR',
    risk_level: 'LR',
    created_at: '2026-05-09T00:00:00Z',
  },
]
