"""phase1_rcm_full_extension

Revision ID: 6c1d441c6eb9
Revises: f657adeb7a6c
Create Date: 2026-05-21 23:55:39.570292+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1d441c6eb9'
down_revision: Union[str, None] = 'f657adeb7a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_processes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('process_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_processes_code'), 'sub_processes', ['code'], unique=True)
    op.create_index(op.f('ix_sub_processes_process_id'), 'sub_processes', ['process_id'], unique=False)
    op.create_table('risks',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assessment_level', sa.String(length=5), nullable=False),
    sa.Column('sub_process_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_process_id'], ['sub_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_code'), 'risks', ['code'], unique=True)
    op.create_index(op.f('ix_risks_sub_process_id'), 'risks', ['sub_process_id'], unique=False)
    op.add_column('controls', sa.Column('risk_id', sa.UUID(), nullable=False))
    op.add_column('controls', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('owner_name', sa.String(length=200), nullable=True))
    op.add_column('controls', sa.Column('is_key_control', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('preventive_detective', sa.String(length=2), nullable=False))
    op.add_column('controls', sa.Column('auto_manual', sa.String(length=2), nullable=False))
    op.add_column('controls', sa.Column('activity_approval', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('activity_verification', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('activity_physical', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('activity_master_data', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('activity_reconciliation', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('activity_supervision', sa.Boolean(), nullable=False))
    op.add_column('controls', sa.Column('related_accounts', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('ipe_relevant', sa.String(length=5), nullable=False))
    op.add_column('controls', sa.Column('related_systems', sa.Text(), nullable=True))
    op.add_column('controls', sa.Column('euc_description', sa.Text(), nullable=True))
    op.alter_column('controls', 'code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('controls', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('controls', 'frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_index('ix_controls_process_id', table_name='controls')
    op.create_index(op.f('ix_controls_risk_id'), 'controls', ['risk_id'], unique=False)
    op.drop_constraint('controls_process_id_fkey', 'controls', type_='foreignkey')
    op.create_foreign_key(None, 'controls', 'risks', ['risk_id'], ['id'])
    op.drop_column('controls', 'process_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('process_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'controls', type_='foreignkey')
    op.create_foreign_key('controls_process_id_fkey', 'controls', 'processes', ['process_id'], ['id'])
    op.drop_index(op.f('ix_controls_risk_id'), table_name='controls')
    op.create_index('ix_controls_process_id', 'controls', ['process_id'], unique=False)
    op.alter_column('controls', 'frequency',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('controls', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('controls', 'code',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('controls', 'euc_description')
    op.drop_column('controls', 'related_systems')
    op.drop_column('controls', 'ipe_relevant')
    op.drop_column('controls', 'related_accounts')
    op.drop_column('controls', 'activity_supervision')
    op.drop_column('controls', 'activity_reconciliation')
    op.drop_column('controls', 'activity_master_data')
    op.drop_column('controls', 'activity_physical')
    op.drop_column('controls', 'activity_verification')
    op.drop_column('controls', 'activity_approval')
    op.drop_column('controls', 'auto_manual')
    op.drop_column('controls', 'preventive_detective')
    op.drop_column('controls', 'is_key_control')
    op.drop_column('controls', 'owner_name')
    op.drop_column('controls', 'objective')
    op.drop_column('controls', 'risk_id')
    op.drop_index(op.f('ix_risks_sub_process_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_code'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_sub_processes_process_id'), table_name='sub_processes')
    op.drop_index(op.f('ix_sub_processes_code'), table_name='sub_processes')
    op.drop_table('sub_processes')
    # ### end Alembic commands ###
