"""phase1_test_workflow_full

Revision ID: 945eba8891e0
Revises: 6c1d441c6eb9
Create Date: 2026-05-22 02:19:15.599263+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945eba8891e0'
down_revision: Union[str, None] = '6c1d441c6eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_risk_assessments',
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('frequency_score', sa.Integer(), nullable=False),
    sa.Column('nature_score', sa.Integer(), nullable=False),
    sa.Column('precision_score', sa.Integer(), nullable=False),
    sa.Column('dependency_score', sa.Integer(), nullable=False),
    sa.Column('automation_score', sa.Integer(), nullable=False),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('prior_year_effectiveness', sa.String(length=20), nullable=False),
    sa.Column('overall_assessment', sa.String(length=20), nullable=False),
    sa.Column('assessor_id', sa.UUID(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'fiscal_year', name='uq_rawc_control_year')
    )
    op.create_index(op.f('ix_control_risk_assessments_assessor_id'), 'control_risk_assessments', ['assessor_id'], unique=False)
    op.create_index(op.f('ix_control_risk_assessments_control_id'), 'control_risk_assessments', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_risk_assessments_fiscal_year'), 'control_risk_assessments', ['fiscal_year'], unique=False)
    op.create_table('test_status_history',
    sa.Column('test_run_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_status_history_changed_by_id'), 'test_status_history', ['changed_by_id'], unique=False)
    op.create_index(op.f('ix_test_status_history_test_run_id'), 'test_status_history', ['test_run_id'], unique=False)
    op.add_column('test_runs', sa.Column('fiscal_year', sa.Integer(), nullable=False))
    op.add_column('test_runs', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('test_runs', sa.Column('wtt_summary', sa.Text(), nullable=True))
    op.add_column('test_runs', sa.Column('existing_process_notes', sa.Text(), nullable=True))
    op.add_column('test_runs', sa.Column('method_inquiry', sa.Boolean(), nullable=False))
    op.add_column('test_runs', sa.Column('method_observation', sa.Boolean(), nullable=False))
    op.add_column('test_runs', sa.Column('method_inspection', sa.Boolean(), nullable=False))
    op.add_column('test_runs', sa.Column('method_reperformance', sa.Boolean(), nullable=False))
    op.add_column('test_runs', sa.Column('population', sa.Text(), nullable=True))
    op.add_column('test_runs', sa.Column('test_frequency', sa.String(length=2), nullable=True))
    op.add_column('test_runs', sa.Column('sample_size', sa.Integer(), nullable=True))
    op.add_column('test_runs', sa.Column('procedure', sa.Text(), nullable=True))
    op.add_column('test_runs', sa.Column('approved_by_id', sa.UUID(), nullable=True))
    op.add_column('test_runs', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('test_runs', 'tester_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('test_runs', 'test_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('test_runs', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_test_runs_fiscal_year'), 'test_runs', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    op.create_unique_constraint('uq_testrun_control_year', 'test_runs', ['control_id', 'fiscal_year'])
    op.create_foreign_key(None, 'test_runs', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_runs', type_='foreignkey')
    op.drop_constraint('uq_testrun_control_year', 'test_runs', type_='unique')
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_fiscal_year'), table_name='test_runs')
    op.alter_column('test_runs', 'result',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('test_runs', 'test_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('test_runs', 'tester_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('test_runs', 'approved_at')
    op.drop_column('test_runs', 'approved_by_id')
    op.drop_column('test_runs', 'procedure')
    op.drop_column('test_runs', 'sample_size')
    op.drop_column('test_runs', 'test_frequency')
    op.drop_column('test_runs', 'population')
    op.drop_column('test_runs', 'method_reperformance')
    op.drop_column('test_runs', 'method_inspection')
    op.drop_column('test_runs', 'method_observation')
    op.drop_column('test_runs', 'method_inquiry')
    op.drop_column('test_runs', 'existing_process_notes')
    op.drop_column('test_runs', 'wtt_summary')
    op.drop_column('test_runs', 'status')
    op.drop_column('test_runs', 'fiscal_year')
    op.drop_index(op.f('ix_test_status_history_test_run_id'), table_name='test_status_history')
    op.drop_index(op.f('ix_test_status_history_changed_by_id'), table_name='test_status_history')
    op.drop_table('test_status_history')
    op.drop_index(op.f('ix_control_risk_assessments_fiscal_year'), table_name='control_risk_assessments')
    op.drop_index(op.f('ix_control_risk_assessments_control_id'), table_name='control_risk_assessments')
    op.drop_index(op.f('ix_control_risk_assessments_assessor_id'), table_name='control_risk_assessments')
    op.drop_table('control_risk_assessments')
    # ### end Alembic commands ###
