"""phase1_remediation_full

Revision ID: d13051e6bcf5
Revises: 945eba8891e0
Create Date: 2026-06-09 07:04:35.496663+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13051e6bcf5'
down_revision: Union[str, None] = '945eba8891e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_assessments',
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('design_score_1', sa.Integer(), nullable=False),
    sa.Column('design_score_2', sa.Integer(), nullable=False),
    sa.Column('design_score_3', sa.Integer(), nullable=False),
    sa.Column('design_score_4', sa.Integer(), nullable=False),
    sa.Column('design_score_5', sa.Integer(), nullable=False),
    sa.Column('design_score_6', sa.Integer(), nullable=False),
    sa.Column('design_score_7', sa.Integer(), nullable=False),
    sa.Column('design_score_8', sa.Integer(), nullable=False),
    sa.Column('overall_design', sa.String(length=20), nullable=False),
    sa.Column('design_notes', sa.Text(), nullable=True),
    sa.Column('assessment_method', sa.String(length=20), nullable=False),
    sa.Column('performer_name', sa.String(length=200), nullable=True),
    sa.Column('performance_frequency', sa.String(length=5), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('assessor_id', sa.UUID(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'fiscal_year', name='uq_design_assessment_control_year')
    )
    op.create_index(op.f('ix_design_assessments_control_id'), 'design_assessments', ['control_id'], unique=False)
    op.create_index(op.f('ix_design_assessments_fiscal_year'), 'design_assessments', ['fiscal_year'], unique=False)
    op.create_table('remediation_status_history',
    sa.Column('remediation_plan_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_status_history_remediation_plan_id'), 'remediation_status_history', ['remediation_plan_id'], unique=False)
    op.add_column('deficiencies', sa.Column('fiscal_year', sa.Integer(), nullable=False, server_default='2025'))
    op.add_column('deficiencies', sa.Column('control_id', sa.UUID(), nullable=True))
    op.add_column('deficiencies', sa.Column('final_conclusion', sa.Text(), nullable=True))
    op.add_column('deficiencies', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deficiencies', sa.Column('confirmed_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_deficiencies_control_id'), 'deficiencies', ['control_id'], unique=False)
    op.create_index(op.f('ix_deficiencies_fiscal_year'), 'deficiencies', ['fiscal_year'], unique=False)
    op.create_foreign_key(None, 'deficiencies', 'controls', ['control_id'], ['id'])
    op.create_foreign_key(None, 'deficiencies', 'users', ['confirmed_by_id'], ['id'])
    op.add_column('remediation_plans', sa.Column('status', sa.String(length=20), nullable=False, server_default='planned'))
    op.add_column('remediation_plans', sa.Column('improvement_description', sa.Text(), nullable=True))
    op.add_column('remediation_plans', sa.Column('priority', sa.String(length=10), nullable=False, server_default='Medium'))
    op.add_column('remediation_plans', sa.Column('owner_opinion', sa.Text(), nullable=True))
    op.add_column('remediation_plans', sa.Column('reviewer_opinion', sa.Text(), nullable=True))
    op.add_column('remediation_plans', sa.Column('approved_by_id', sa.UUID(), nullable=True))
    op.add_column('remediation_plans', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_remediation_plans_status'), 'remediation_plans', ['status'], unique=False)
    op.create_foreign_key(None, 'remediation_plans', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'remediation_plans', type_='foreignkey')
    op.drop_index(op.f('ix_remediation_plans_status'), table_name='remediation_plans')
    op.drop_column('remediation_plans', 'approved_at')
    op.drop_column('remediation_plans', 'approved_by_id')
    op.drop_column('remediation_plans', 'reviewer_opinion')
    op.drop_column('remediation_plans', 'owner_opinion')
    op.drop_column('remediation_plans', 'priority')
    op.drop_column('remediation_plans', 'improvement_description')
    op.drop_column('remediation_plans', 'status')
    op.drop_constraint(None, 'deficiencies', type_='foreignkey')
    op.drop_constraint(None, 'deficiencies', type_='foreignkey')
    op.drop_index(op.f('ix_deficiencies_fiscal_year'), table_name='deficiencies')
    op.drop_index(op.f('ix_deficiencies_control_id'), table_name='deficiencies')
    op.drop_column('deficiencies', 'confirmed_by_id')
    op.drop_column('deficiencies', 'confirmed_at')
    op.drop_column('deficiencies', 'final_conclusion')
    op.drop_column('deficiencies', 'control_id')
    op.drop_column('deficiencies', 'fiscal_year')
    op.drop_index(op.f('ix_remediation_status_history_remediation_plan_id'), table_name='remediation_status_history')
    op.drop_table('remediation_status_history')
    op.drop_index(op.f('ix_design_assessments_fiscal_year'), table_name='design_assessments')
    op.drop_index(op.f('ix_design_assessments_control_id'), table_name='design_assessments')
    op.drop_table('design_assessments')
    # ### end Alembic commands ###
